- name: 'Auto start Motion daemon'
  lineinfile:
    line: 'start_motion_daemon=yes'
    path: /etc/default/motion
    regexp: '^start_motion_daemon'
    state: present
  when: motion_server_enabled

- name: 'Do not autostart Motion daemon'
  lineinfile:
    line: 'start_motion_daemon=no'
    path: /etc/default/motion
    regexp: '^start_motion_daemon'
    state: present
  when: motion_server_enabled == false

- name: 'Allow Motion connections from anywhere'
  lineinfile:
    line: 'stream_localhost off'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost'
    state: present
  when: motion_server_localhost == false

- name: 'Allow Motion connections from localhost only'
  lineinfile:
    line: 'stream_localhost on'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost'
    state: present
  when: motion_server_localhost == true

- name: 'Set stream quality'
  lineinfile:
    line: 'stream_quality {{ motion_stream_quality }}'
    path: /etc/motion/motion.conf
    regexp: '^stream_quality'
    state: present
