- name: 'Auto start Motion daemon'
  lineinfile:
    line: 'start_motion_daemon=yes'
    path: /etc/default/motion
    regexp: '^start_motion_daemon'
    state: present
  when: motion_server_enabled

- name: 'Do not autostart Motion daemon'
  lineinfile:
    line: 'start_motion_daemon=no'
    path: /etc/default/motion
    regexp: '^start_motion_daemon'
    state: present
  when: motion_server_enabled == false

- name: 'Allow Motion connections from anywhere'
  lineinfile:
    line: 'stream_localhost off'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost '
    state: present
  when: motion_server_localhost == false

- name: 'Allow Motion connections from localhost only'
  lineinfile:
    line: 'stream_localhost on'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost '
    state: present
  when: motion_server_localhost == true

#
# Capture Device Options
#

- name: "Update motion image width"
  lineinfile:
    line: "width {{ motion_server_image_width }}"
    path: /etc/motion/motion.conf
    regexp: '^width '
    state: present

- name: "Update motion image height"
  lineinfile:
    line: "height {{ motion_server_image_height }}"
    path: /etc/motion/motion.conf
    regexp: '^height '
    state: present

- lineinfile:
    line: "framerate {{ motion_server_framerate }}"
    path: /etc/motion/motion.conf
    regexp: '^framerate '
    state: present

- lineinfile:
    line: "quality {{ motion_server_quality }}"
    path: /etc/motion/motion.conf
    regexp: '^quality '
    state: present

- name: 'Motion setting: auto_brightness'
  lineinfile:
    line: "auto_brightness {{ motion_server_auto_brightness }}"
    path: /etc/motion/motion.conf
    regexp: '^auto_brightness '
    state: present

- name: 'Motion setting: brightness'
  lineinfile:
    line: "brightness {{ motion_server_brightness }}"
    path: /etc/motion/motion.conf
    regexp: '^brightness '
    state: present

#
# Motion Detection
#
- name: 'Motion setting: lightswitch'
  lineinfile:
    line: "lightswitch {{ motion_server_lightswitch }}"
    path: /etc/motion/motion.conf
    regexp: '^lightswitch '
    state: present

- name: 'Motion setting: pre_capture'
  lineinfile:
    line: "pre_capture {{ motion_server_pre_capture }}"
    path: /etc/motion/motion.conf
    regexp: '^pre_capture '
    state: present

- name: 'Motion setting: post_capture'
  lineinfile:
    line: "post_capture {{ motion_server_post_capture }}"
    path: /etc/motion/motion.conf
    regexp: '^post_capture '
    state: present

- name: 'Motion setting: event_gap'
  lineinfile:
    line: "event_gap {{ motion_server_event_gap }}"
    path: /etc/motion/motion.conf
    regexp: '^event_gap '
    state: present

- name: 'Motion setting: max_movie_time'
  lineinfile:
    line: "max_movie_time {{ motion_server_max_movie_time }}"
    path: /etc/motion/motion.conf
    regexp: '^max_movie_time '
    state: present

#
# Image File Output
#
- name: 'Motion setting: output_pictures'
  lineinfile:
    line: "output_pictures {{ motion_server_output_pictures }}"
    path: /etc/motion/motion.conf
    regexp: '^output_pictures '
    state: present

#
# ffmpeg
#
- name: 'Motion setting: ffmpeg_output_movies'
  lineinfile:
    line: "ffmpeg_output_movies {{ motion_server_ffmpeg_output_movies }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_output_movies '
    state: present

- name: 'Motion setting: ffmpeg_video_codec'
  lineinfile:
    line: "ffmpeg_video_codec {{ motion_server_ffmpeg_video_codec }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_video_codec '
    state: present

- name: 'Motion setting: ffmpeg_timelapse'
  lineinfile:
    line: "ffmpeg_timelapse {{ motion_server_ffmpeg_timelapse }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_timelapse '
    state: present

- name: 'Motion setting: ffmpeg_timelapse_mode'
  lineinfile:
    line: "ffmpeg_timelapse_mode {{ motion_server_ffmpeg_timelapse_mode }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_timelapse_mode '
    state: present

- name: 'Motion setting: ffmpeg_duplicate_frames'
  lineinfile:
    line: "ffmpeg_duplicate_frames {{ motion_server_ffmpeg_duplicate_frames }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_duplicate_frames '
    state: present

- name: 'Motion setting: ffmpeg_bps'
  lineinfile:
    line: "ffmpeg_bps {{ motion_server_ffmpeg_bps }}"
    path: /etc/motion/motion.conf
    regexp: '^ffmpeg_bps '
    state: present

#
# Live Stream Server
#
- name: 'Motion setting: stream_quality'
  lineinfile:
    line: 'stream_quality {{ motion_server_stream_quality }}'
    path: /etc/motion/motion.conf
    regexp: '^stream_quality '
    state: present

- name: 'Motion setting: stream_maxrate'
  lineinfile:
    line: 'stream_maxrate {{ motion_server_stream_maxrate }}'
    path: /etc/motion/motion.conf
    regexp: '^stream_maxrate '
    state: present

- name: 'Motion setting: stream_limit'
  lineinfile:
    line: 'stream_limit {{ motion_server_stream_limit }}'
    path: /etc/motion/motion.conf
    regexp: '^stream_limit '
    state: present

#
# HTTP based control
#
- name: 'Motion setting: webcontrol_localhost'
  lineinfile:
    line: 'webcontrol_localhost {{ motion_server_webcontrol_localhost }}'
    path: /etc/motion/motion.conf
    regexp: '^webcontrol_localhost '
    state: present

#
# Target Directories
#
- name: 'Motion setting: snapshot_filename'
  lineinfile:
    line: 'snapshot_filename {{ motion_server_snapshot_filename }}'
    path: /etc/motion/motion.conf
    regexp: '^snapshot_filename '
    state: present

- name: 'Motion setting: picture_filename'
  lineinfile:
    line: 'picture_filename {{ motion_server_picture_filename }}'
    path: /etc/motion/motion.conf
    regexp: '^picture_filename '
    state: present

- name: 'Motion setting: movie_filename'
  lineinfile:
    line: 'movie_filename {{ motion_server_movie_filename }}'
    path: /etc/motion/motion.conf
    regexp: '^movie_filename '
    state: present

- name: 'Motion setting: timelapse_filename'
  lineinfile:
    line: 'timelapse_filename {{ motion_server_timelapse_filename }}'
    path: /etc/motion/motion.conf
    regexp: '^timelapse_filename '
    state: present
