- name: 'Auto start Motion daemon'
  lineinfile:
    line: 'start_motion_daemon=yes'
    path: /etc/default/motion
    regexp: '^start_motion_daemon'
    state: present

- name: 'Allow Motion connections from anywhere'
  lineinfile:
    line: 'stream_localhost off'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost'
    state: present
  when: not motion_server_localhost

- name: 'Allow Motion connections from localhost only'
  lineinfile:
    line: 'stream_localhost off'
    path: /etc/motion/motion.conf
    regexp: '^stream_localhost'
    state: present
  when: motion_server_localhost

- name: 'Set stream quality'
  lineinfile:
    line: 'stream_quality {{ motion_stream_quality }}'
    path: /etc/motion/motion.conf
    regexp: '^stream_quality'
    state: present
