- name: "Install VLC"
  apt: name=vlc state=present

- name: 'Install Motion'
  apt: name=motion state=present

#
# Helpful utility
#
- name: Install motion restarter
  template:
    dest: /usr/local/sbin/restart-motion-service
    src: usr/local/sbin/restart-motion-service.j2
    mode: 0755
